name: "Kindle Image Server"
version: "1.0.0"
slug: "kindle_image_server"
description: "Create a dynamic Kindle dashboard image from Home Assistant input_text."
startup: services
boot: auto
homeassistant_api: true
init: false
panel_icon: mdi:television
options:
  sensor: "input_text.dashboard_message"
schema:
  sensor: str
ports:
  5000/tcp: 5000
